language: objective-c
osx_image: xcode6.4
before_install:
  - brew update
script:
  - brew install https://gist.githubusercontent.com/oleander/daf23e66068e417371af8ec8d13ef215/raw/a1e0d30e125bab182f98a3cf786bf129a616a8ad/Couchsurfing.rb
  - couchsurfing help
  - cs-location
